### ISSUE TITLE
Dockerfile does not build from local copy

### ISSUE THREAD

**Issue by KonradHoeffner** [ggonnella/fastsubtrees#6]
In `docker/Dockerfile`:

    RUN pip install 'ntmirror @ git+https://github.com/ggonnella/fastsubtrees/#subdirectory=ntmirror'
    RUN ntmirror-download ntdumpdir
    RUN pip install 'fastsubtrees @ git+https://github.com/ggonnella/fastsubtrees'

This builds from the latest copy on Git but this causes three major problems:

1. local fixes that are not yet pushed to Git cannot be tested
2. when checking out an older state of fastsubtrees, the Dockerfile is not in sync with the fastsubtrees, which may cause any number of detectable or undetectable errors
3. you cannot use the Dockerfile as is in a fork
4. it can break new versions when old versions are in the Docker build cache (see issue #5)

I recommend building from the local filesystem instead to circumvent all those errors.

**Comment by ggonnella** [comment]
This was fixed now in commit d5ea4cd78fccf732861650416a317d200c7f09b2

**Comment by ggonnella** [comment]
@KonradHoeffner
I close this issue, since the new Docker image does that

Feel free to reopen, if necessary
