### ISSUE TITLE
scripts and commands too complicated

### ISSUE THREAD

**Issue by KonradHoeffner** [ggonnella/fastsubtrees#7]
There is a mix of makefiles, pip install, external dependencies, Docker and more and some of it is inside other folders.
I would prefer it if I would never have to mix things, for example when I'm using the Docker image I should not need to execute a makefile because Docker can wrap all of that in the container.
Then for example for Docker it could just be:

    docker run fastsubtrees test
    docker run fastsubtrees benchmark
    docker run fastsubtrees ...

**Comment by KonradHoeffner** [comment]
Thanks, I will try it out!

This method looks way easier to use.
However I'm not sure if it is really the most simple solution to separate the container run and exec parts.
Docker uses a layered cache and the data preparation steps should occur at the end, so there shouldn't be any cache invalidation in the parts that already exist in the Dockerfile, because the existing parts would be in the inner layers that are described above the data preparation steps.
As for speeding up maintenance and development, this could be done with a volume as well.
This would also allow keeping the data when the container is removed, and actually allow saving even more time, since the data could be decoupled with the rest of the program and then a new version of fastsubtrees could directly use old data, however then I'm not sure if the compatibility would be guaranteed, it could be necessary to delete the volume in some cases.
Another way could be to use Docker Compose with data containers, but I'm not sure if that would be worth it.

However I do not want to overcomplicate your design, those are just some thoughts, this way is totally fine as well!

**Comment by KonradHoeffner** [comment]
On Docker version 20.10.18, build b40c2f6b5d on Arch Linux, `docker build --tag "fastsubtreesC"` does not work however, it needs a path argument and the tag needs to be lowercase, like `docker build . fastsubtrees`.

**Comment by KonradHoeffner** [comment]
```
docker build --tag "fastsubtrees"
docker run -p 8050:8050 --detach --name fastsubtrees fastsubtrees

docker exec fastsubtrees tests
docker exec fastsubtrees benchmark
docker exec fastsubtrees start-example-app
```

- [x] tests
- [ ] benchmark
- [ ] app

**Comment by ggonnella** [comment]
Thank you, indeed the line ``docker build --tag "fastsubtreesC"`` was intended to be ``docker build --tag "fastsubtrees"``, that was a typo, since ``fastsubtreesC`` is, in my example, the name of the container and not of the image.
